# Generated by Django 3.1.6 on 2021-02-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atracao', '0001_initial'),
        ('endereco', '0001_initial'),
        ('comentario', '0001_initial'),
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('descricao', models.TextField()),
                ('aprovacao', models.BooleanField(default=False)),
                ('atracoes', models.ManyToManyField(to='atracao.Atracao')),
                ('avaliacoes', models.ManyToManyField(to='avaliacao.Avaliacao')),
                ('comentarios', models.ManyToManyField(to='comentario.Comentario')),
                ('enderecos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
            ],
        ),
    ]
